export const docSections = [
  {
    id: 'introduction',
    file: '01_introduction',
    title: 'Introduction',
    icon: '📖',
    summary: 'What Vibrante-Node is, what problems it solves, and how the node + exec-pin model works.',
    items: ['What is Vibrante-Node?', 'Core concepts: nodes, pins, wires', 'Exec flow vs data flow', 'When to use Vibrante-Node'],
  },
  {
    id: 'getting-started',
    file: '02_getting_started',
    title: 'Getting Started',
    icon: '🚀',
    summary: 'Installation from source, first launch, configuring Houdini integration, and running your first workflow.',
    items: ['Requirements (Python 3.10+, PyQt5)', 'Installation from source', 'First launch walkthrough', 'Houdini package setup'],
  },
  {
    id: 'user-guide',
    file: '03_user_guide',
    title: 'User Guide',
    icon: '🎮',
    summary: 'Full guide to the Vibrante-Node UI: canvas, library, log panel, mini-map, canvas search, and keyboard shortcuts.',
    items: ['Canvas navigation', 'Node library', 'Connecting nodes', 'Execution log', 'Mini-map (Ctrl+M)', 'Canvas Search (Ctrl+F)', 'Keyboard shortcuts'],
  },
  {
    id: 'workflow-tutorials',
    file: '04_workflow_tutorials',
    title: 'Workflow Tutorials',
    icon: '🎬',
    summary: 'Step-by-step tutorials for building real pipelines: Houdini, Maya, Prism, and AI orchestration workflows.',
    items: ['Houdini geometry workflow', 'Maya batch export', 'Prism asset publishing', 'AI feedback processing', 'Multi-shot rendering'],
  },
  {
    id: 'node-development',
    file: '05_node_development',
    title: 'Node Development',
    icon: '🔧',
    summary: 'How to create custom nodes: BaseNode API, JSON format, exec pins, port types, and the Node Builder GUI.',
    items: ['BaseNode class reference', 'JSON node format', 'Port types and widgets', 'execute() return values', 'Node Builder GUI (Ctrl+E)', 'Registering and loading nodes'],
  },
  {
    id: 'backend-architecture',
    file: '06_backend_architecture',
    title: 'Backend Architecture',
    icon: '⚙️',
    summary: 'How the async execution engine works: DAG resolution, signal flow, asyncio integration, and error handling.',
    items: ['NetworkExecutor', 'Async DAG execution', 'Signal/slot model', 'Error propagation', 'GroupNode execution', 'Headless mode'],
  },
  {
    id: 'frontend-architecture',
    file: '07_frontend_architecture',
    title: 'Frontend Architecture',
    icon: '🎨',
    summary: 'The PyQt5 UI: scene graph, NodeWidget, Edge/wire rendering, live wire inspector, mini-map, and theming.',
    items: ['NodeScene / NodeView', 'NodeWidget rendering', 'Edge and port drawing', 'Live Wire Inspector', 'Mini-map (MiniMap)', 'Dark/Light theming'],
  },
  {
    id: 'api-reference',
    file: '08_api_reference',
    title: 'API Reference',
    icon: '📚',
    summary: 'Complete API for BaseNode, HouBridge, PrismCore resolver, WorkflowModel, and all built-in utility functions.',
    items: ['BaseNode API', 'HouBridge 18 methods', 'resolve_prism_core()', 'WorkflowModel schema', 'NodeRegistry', 'ConfigManager'],
  },
  {
    id: 'advanced-topics',
    file: '09_advanced_topics',
    title: 'Advanced Topics',
    icon: '🔬',
    summary: 'GroupNode subgraphs, autosave/crash recovery, headless execution, workflow serialization, and the Houdini plugin architecture.',
    items: ['GroupNode / Subgraph (Ctrl+Shift+G)', 'Autosave & crash recovery', 'Headless workflow execution', 'Workflow JSON serialization', 'Houdini plugin architecture', 'Environment variables'],
  },
  {
    id: 'contribution',
    file: '10_contribution_guide',
    title: 'Contribution Guide',
    icon: '🤝',
    summary: 'How to contribute: code style, testing, PR process, and adding new node categories or integrations.',
    items: ['Code style (PEP 8)', 'Writing tests', 'PR process', 'Adding new nodes', 'Adding new DCC integrations', 'Documentation standards'],
  },
  {
    id: 'troubleshooting',
    file: '11_troubleshooting',
    title: 'Troubleshooting',
    icon: '🔍',
    summary: 'Common issues: Houdini connection failures, port bind errors, QScintilla missing, PyQt5 conflicts, and crash recovery.',
    items: ['Houdini bridge not connecting', 'Port already in use', 'QScintilla not installed', 'PyQt5 / PySide2 conflict', 'Reading crash.log', 'Environment variable checklist'],
  },
  {
    id: 'examples',
    file: '12_examples_library',
    title: 'Examples Library',
    icon: '📁',
    summary: 'Ready-to-use .vnw workflow files and custom node examples covering all integration categories.',
    items: ['Houdini examples', 'Maya batch examples', 'Prism workflow examples', 'AI orchestration examples', 'Custom node examples', 'Test workflows'],
  },
  {
    id: 'general-automation',
    file: '13_general_purpose_automation',
    title: 'General-Purpose Automation',
    icon: '🤖',
    summary: 'Using Vibrante-Node outside of DCC tools: file operations, HTTP APIs, JSON processing, and Python scripting nodes.',
    items: ['File I/O nodes', 'HTTP request node', 'JSON parse/format', 'ForEach and WhileLoop', 'SetVariable/GetVariable', 'Console Print and logging'],
  },
  {
    id: 'custom-nodes-api',
    file: '14_custom_nodes_api',
    title: 'Custom Nodes API',
    icon: '🧩',
    summary: 'The complete custom node API: all add_input() / add_output() options, log_error(), set_output(), parameters dict, and the Node Builder.',
    items: ['add_input() signature', 'add_output() signature', 'log_error() / log_warning()', 'set_output() for GroupOutNode', 'self.parameters dict', 'register_node() contract'],
  },
]

export type DocSection = (typeof docSections)[number]
